# Replace the "â¯" symbol in the prompt with "âœ"
[character]                
success_symbol = "[â–² ](green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[â–² ](red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[nodejs]
disabled = true

[git_status]
disabled = true

[git_branch]
style = "green"

[directory]
style = "cyan"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
disabled = false
